// dxil_asm: assembles DXIL text (the output of `dxc -dumpbin`, edited or not) into a signed DXIL
// container, using DXC's own assembler (IDxcAssembler) and validator (IDxcValidator, dxil.dll).
//
// Usage: dxil_asm <dxc bin dir> <input.ll> <output.cso> [--parts-from original.cso] [--header out.h symbol]
//   --parts-from  copies the root signature (RTS0) and the debug name (ILDN) of the original
//                 container and drops the reflection part (STAT) the assembler adds, so the result
//                 has the same parts as the game's shader. The validator then also checks that the
//                 root signature fits the shader.
//   --header      also writes the bytecode as a C array, like `dxc -Fh`.
// Exit code 0 only when assembly and validation both succeed.

#include <windows.h>
#include <unknwn.h>
#include <objidl.h>
#include <dxcapi.h>

#include <cstdint>
#include <cstdio>
#include <cstring>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

namespace
{
    // IIDs spelled out: llvm-mingw has no __uuidof for the DXC interfaces.
    const GUID kIID_IDxcUtils = { 0x4605c4cb, 0x2019, 0x492a, { 0xad, 0xa4, 0x65, 0xf2, 0x0b, 0xb7, 0xd6, 0x7f } };
    const GUID kIID_IDxcAssembler = { 0x091f7a26, 0x1c1f, 0x4948, { 0x90, 0x4b, 0xe6, 0xe3, 0xa8, 0xa7, 0x71, 0xd5 } };
    const GUID kIID_IDxcValidator = { 0xa6e82bd2, 0x1fd7, 0x4826, { 0x98, 0x11, 0x28, 0x57, 0xe7, 0x97, 0xf4, 0x9a } };
    const GUID kIID_IDxcContainerBuilder = { 0x334b1f50, 0x2292, 0x4b35, { 0x99, 0xa1, 0x25, 0x58, 0x8d, 0x8c, 0x17, 0xfe } };

    template <typename T>
    struct com
    {
        T *p = nullptr;
        ~com() { if (p) p->Release(); }
        T **out() { return &p; }
        T *operator->() const { return p; }
    };

    std::string errors_of(IDxcOperationResult *r)
    {
        com<IDxcBlobEncoding> e;
        if (r == nullptr || FAILED(r->GetErrorBuffer(e.out())) || e.p == nullptr || e->GetBufferSize() == 0)
            return {};
        return std::string(static_cast<const char *>(e->GetBufferPointer()), e->GetBufferSize());
    }

    bool read_file(const std::string &path, std::string &data)
    {
        std::ifstream f(path, std::ios::binary);
        if (!f)
            return false;
        std::stringstream ss;
        ss << f.rdbuf();
        data = ss.str();
        return true;
    }

    bool write_file(const std::string &path, const void *data, size_t size)
    {
        std::ofstream f(path, std::ios::binary);
        f.write(static_cast<const char *>(data), std::streamsize(size));
        return bool(f);
    }

    bool write_header(const std::string &path, const std::string &symbol, const unsigned char *data, size_t size)
    {
        std::ofstream f(path);
        f << "// Generated by dxil_asm. Do not edit.\n#pragma once\nconst unsigned char " << symbol << "[] = {";
        for (size_t i = 0; i < size; ++i)
        {
            if (i % 16 == 0)
                f << "\n    ";
            char b[8];
            snprintf(b, sizeof(b), "0x%02x,", data[i]);
            f << b;
        }
        f << "\n};\n";
        return bool(f);
    }

    // Payload of one part of a DXBC/DXIL container, empty when absent.
    std::string container_part(const std::string &c, uint32_t fourcc)
    {
        if (c.size() < 32 || memcmp(c.data(), "DXBC", 4) != 0)
            return {};
        uint32_t count = 0;
        memcpy(&count, c.data() + 28, 4);
        for (uint32_t i = 0; i < count && 32 + 4 * (i + 1) <= c.size(); ++i)
        {
            uint32_t offset = 0, code = 0, size = 0;
            memcpy(&offset, c.data() + 32 + 4 * i, 4);
            if (offset + 8 > c.size())
                return {};
            memcpy(&code, c.data() + offset, 4);
            memcpy(&size, c.data() + offset + 4, 4);
            if (code == fourcc && offset + 8 + size <= c.size())
                return c.substr(offset + 8, size);
        }
        return {};
    }
}

int main(int argc, char **argv)
{
    if (argc < 4)
    {
        fprintf(stderr, "usage: dxil_asm <dxc bin dir> <input.ll> <output.cso> [--parts-from original.cso] [--header out.h symbol]\n");
        return 2;
    }
    const std::string bin = argv[1], input = argv[2], output = argv[3];
    std::string parts_from, header, symbol;
    for (int i = 4; i < argc; ++i)
    {
        if (strcmp(argv[i], "--parts-from") == 0 && i + 1 < argc)
            parts_from = argv[++i];
        else if (strcmp(argv[i], "--header") == 0 && i + 2 < argc)
        {
            header = argv[++i];
            symbol = argv[++i];
        }
        else
        {
            fprintf(stderr, "unknown argument %s\n", argv[i]);
            return 2;
        }
    }

    // Altered search path: the DLLs' own dependencies resolve from their folder, not from ours.
    HMODULE compiler = LoadLibraryExA((bin + "\\dxcompiler.dll").c_str(), nullptr, LOAD_WITH_ALTERED_SEARCH_PATH);
    const DWORD compiler_error = GetLastError();
    HMODULE dxil = LoadLibraryExA((bin + "\\dxil.dll").c_str(), nullptr, LOAD_WITH_ALTERED_SEARCH_PATH);
    if (compiler == nullptr || dxil == nullptr)
    {
        fprintf(stderr, "cannot load %s from %s (error %lu)\n", compiler == nullptr ? "dxcompiler.dll" : "dxil.dll", bin.c_str(),
                static_cast<unsigned long>(compiler == nullptr ? compiler_error : GetLastError()));
        return 3;
    }
    auto create_compiler = reinterpret_cast<DxcCreateInstanceProc>(GetProcAddress(compiler, "DxcCreateInstance"));
    auto create_dxil = reinterpret_cast<DxcCreateInstanceProc>(GetProcAddress(dxil, "DxcCreateInstance"));

    std::string text, original;
    if (!read_file(input, text))
    {
        fprintf(stderr, "cannot read %s\n", input.c_str());
        return 3;
    }
    if (!parts_from.empty() && !read_file(parts_from, original))
    {
        fprintf(stderr, "cannot read %s\n", parts_from.c_str());
        return 3;
    }

    com<IDxcUtils> utils;
    com<IDxcAssembler> assembler;
    com<IDxcValidator> validator;
    if (FAILED(create_compiler(CLSID_DxcUtils, kIID_IDxcUtils, reinterpret_cast<void **>(utils.out()))) ||
        FAILED(create_compiler(CLSID_DxcAssembler, kIID_IDxcAssembler, reinterpret_cast<void **>(assembler.out()))) ||
        FAILED(create_dxil(CLSID_DxcValidator, kIID_IDxcValidator, reinterpret_cast<void **>(validator.out()))))
    {
        fprintf(stderr, "DxcCreateInstance failed\n");
        return 3;
    }

    com<IDxcBlobEncoding> source;
    if (FAILED(utils->CreateBlob(text.data(), UINT32(text.size()), CP_UTF8, source.out())))
    {
        fprintf(stderr, "CreateBlob failed\n");
        return 3;
    }

    com<IDxcOperationResult> assembled;
    HRESULT status = E_FAIL;
    if (FAILED(assembler->AssembleToContainer(source.p, assembled.out())) || FAILED(assembled->GetStatus(&status)) || FAILED(status))
    {
        fprintf(stderr, "assembly failed (0x%08lx)\n%s\n", static_cast<unsigned long>(status), errors_of(assembled.p).c_str());
        return 1;
    }
    com<IDxcBlob> container;
    assembled->GetResult(container.out());

    if (!original.empty())
    {
        com<IDxcContainerBuilder> builder;
        if (FAILED(create_compiler(CLSID_DxcContainerBuilder, kIID_IDxcContainerBuilder, reinterpret_cast<void **>(builder.out()))) ||
            FAILED(builder->Load(container.p)))
        {
            fprintf(stderr, "container builder failed to load the assembled container\n");
            return 1;
        }
        builder->RemovePart(DXC_PART_REFLECTION_DATA);   // not in the game's shader
        for (uint32_t fourcc : { uint32_t(DXC_PART_ROOT_SIGNATURE), uint32_t(DXC_PART_PDB_NAME) })
        {
            const std::string part = container_part(original, fourcc);
            if (part.empty())
                continue;
            com<IDxcBlobEncoding> blob;
            if (FAILED(utils->CreateBlob(part.data(), UINT32(part.size()), 0, blob.out())) || FAILED(builder->AddPart(fourcc, blob.p)))
            {
                fprintf(stderr, "cannot add part 0x%08x from %s\n", fourcc, parts_from.c_str());
                return 1;
            }
        }
        com<IDxcOperationResult> serialized;
        status = E_FAIL;
        if (FAILED(builder->SerializeContainer(serialized.out())) || FAILED(serialized->GetStatus(&status)) || FAILED(status))
        {
            fprintf(stderr, "container serialisation failed (0x%08lx)\n%s\n", static_cast<unsigned long>(status), errors_of(serialized.p).c_str());
            return 1;
        }
        com<IDxcBlob> rebuilt;
        serialized->GetResult(rebuilt.out());
        std::swap(container.p, rebuilt.p);
    }

    // Validation signs the container (hash) in place; D3D12 rejects unsigned DXIL.
    com<IDxcOperationResult> validated;
    status = E_FAIL;
    if (FAILED(validator->Validate(container.p, DxcValidatorFlags_InPlaceEdit, validated.out())) || FAILED(validated->GetStatus(&status)) || FAILED(status))
    {
        fprintf(stderr, "validation failed (0x%08lx)\n%s\n", static_cast<unsigned long>(status), errors_of(validated.p).c_str());
        return 1;
    }

    const auto *data = static_cast<const unsigned char *>(container->GetBufferPointer());
    const size_t size = container->GetBufferSize();
    if (!write_file(output, data, size))
    {
        fprintf(stderr, "cannot write %s\n", output.c_str());
        return 3;
    }
    if (!header.empty() && !write_header(header, symbol, data, size))
    {
        fprintf(stderr, "cannot write %s\n", header.c_str());
        return 3;
    }
    printf("ok: %s -> %s (%zu bytes, assembled%s and validated)\n", input.c_str(), output.c_str(), size, original.empty() ? "" : ", parts copied");
    return 0;
}
